import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Sales Data Analysis Project started!")
print("Python is working successfully.")
# Load the sales dataset
df = pd.read_csv("sales_data.csv",encoding="utf-8")

# Display the first 5 rows
print("\nFirst 5 rows of the dataset:")
print(df.head())

# Display dataset information
print("\nDataset Information:")
print(df.info())
# Calculate total sales for each transaction
df["Total_Sales"] = df["Quantity"] * df["Price"]

# Calculate overall sales
total_sales = df["Total_Sales"].sum()

print("\nTotal Sales:")
print("₹", total_sales)
# Find total quantity sold for each product
product_sales = df.groupby("Product")["Quantity"].sum()

print("\nQuantity Sold by Product:")
print(product_sales)

# Find the best-selling product
best_product = product_sales.idxmax()
best_quantity = product_sales.max()

print("\nBest-Selling Product:")
print(best_product)
print("Quantity Sold:", best_quantity)
# Calculate revenue generated by each product
revenue_by_product = df.groupby("Product")["Total_Sales"].sum()

print("\nRevenue by Product:")
print(revenue_by_product)

# Find the product with highest revenue
top_revenue_product = revenue_by_product.idxmax()
top_revenue = revenue_by_product.max()

print("\nHighest Revenue Product:")
print(top_revenue_product)
print("Revenue: ₹", top_revenue)
# Product-wise revenue chart
plt.figure(figsize=(8, 5))

revenue_by_product.plot(kind="bar")

plt.title("Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue (₹)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.close()
# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Create Month column
df["Month"] = df["Date"].dt.to_period("M").astype(str)

# Calculate monthly revenue
monthly_sales = df.groupby("Month")["Total_Sales"].sum()

print("\nMonthly Sales:")
print(monthly_sales)
# Monthly sales trend chart
plt.figure(figsize=(8, 5))

monthly_sales.plot(kind="line", marker="o")

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales Revenue (₹)")
plt.grid(True)
plt.tight_layout()

plt.show()
df["Revenue"] = df["Quantity"] * df["Price"]
# Category-wise Sales
category_sales = df.groupby("Category")["Revenue"].sum()

plt.figure(figsize=(8, 5))
category_sales.plot(kind="bar")

plt.title("Category-wise Sales")
plt.xlabel("Category")
plt.ylabel("Sales Revenue (₹)")
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()
plt.figure(figsize=(8, 5))
category_sales.plot(kind="bar")

plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales Revenue (₹)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
category_sales = df.groupby("Category")["Total_Sales"].sum()
print(category_sales)
# Quantity sold by product
product_quantity = df.groupby("Product")["Quantity"].sum()

print("\nQuantity Sold by Product:")
print(product_quantity)
# Top selling product
top_product = df.groupby("Product")["Total_Sales"].sum().idxmax()
top_sales = df.groupby("Product")["Total_Sales"].sum().max()

print("\nTop Selling Product:")
print(top_product)
print("Sales:", top_sales)
# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())
# Machine Learning - Sales Prediction

from sklearn.linear_model import LinearRegression

ml_data = monthly_sales.reset_index()

ml_data["Month_Number"] = range(1, len(ml_data) + 1)

X = ml_data[["Month_Number"]]
y = ml_data["Total_Sales"]

model = LinearRegression()
model.fit(X, y)

# Predict next month's sales
next_month = [[len(ml_data) + 1]]

predicted_sales = model.predict(next_month)[0]

print("\nPredicted Sales for Next Month:")
print("₹", round(predicted_sales, 2))
# Prediction Graph

plt.figure(figsize=(8, 5))

plt.plot(
    ml_data["Month_Number"],
    ml_data["Total_Sales"],
    marker="o",
    label="Actual Sales"
)

plt.scatter(
    len(ml_data) + 1,
    predicted_sales,
    s=100,
    label="Predicted Sales"
)

plt.title("Actual vs Predicted Sales")
plt.xlabel("Month Number")
plt.ylabel("Sales Revenue (₹)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
print("\n========== PROJECT SUMMARY ==========")
print("Total Sales: ₹", total_sales)
print("Highest Revenue Product:", top_revenue_product)
print("Highest Product Revenue: ₹", top_revenue)
print("Predicted Next Month Sales: ₹", round(predicted_sales, 2))
print("=====================================")